In [1]:
import torch
import torch.nn.functional as F
from torch import nn

# 不带参数的层

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))


tensor([-2., -1.,  0.,  1.,  2.])

将层作为组件合并到更复杂的模型中

In [4]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [5]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(9.3132e-10, grad_fn=<MeanBackward0>)

# 带参数的层

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

实例化MyLinear类并访问其模型参数

In [7]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-1.1327,  0.8955,  0.4852],
        [-0.7297, -0.4861, -0.5127],
        [ 1.5910,  1.6093, -1.7256],
        [ 2.8227, -1.3079,  1.3201],
        [ 1.7764,  0.3867,  0.2473]], requires_grad=True)

使⽤⾃定义层直接执⾏前向传播计算

In [8]:
linear(torch.rand(2, 5))

tensor([[2.2984, 3.0244, 0.0000],
        [0.4639, 2.5692, 0.0000]])

使⽤⾃定义层构建模型

In [9]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[15.2578],
        [ 5.8301]])